CREATE DATABASE DB_TICKETS
GO
    USE DB_TICKETS
GO
    CREATE TABLE TBL_ROLES(
        ID INT IDENTITY(1, 1) PRIMARY KEY,
        ROL VARCHAR(50) NOT NULL,
        AUX_MONTO_MINIMO DECIMAL(10, 2),
        AUX_MONTO_MAXIMI DECIMAL(10, 2)
    )
GO
    CREATE TABLE TBL_USUARIOS (
        ID INT IDENTITY(1, 1) PRIMARY KEY,
        CORREO VARCHAR(50) NOT NULL,
        CONTRASENA VARCHAR(1000) NOT NULL,
        ROL INT NOT NULL,
        CONSTRAINT FK_ROL_USUARIO FOREIGN KEY (ROL) REFERENCES TBL_ROLES (ID)
    )
GO
    CREATE TABLE TBL_SOLICITUDES(
        ID INT IDENTITY(1, 1) PRIMARY KEY,
        FECHA DATE NOT NULL,
        ID_USUARIO INT NOT NULL,
        NOMBRE_PRODUCTO VARCHAR(200) NOT NULL,
        PRECIO DECIMAL(10, 2) NOT NULL,
        DESCRIPCION VARCHAR(1000) NOT NULL,
        RAZON_COMPRA VARCHAR(200) NOT NULL,
        LUGAR_COMPRA VARCHAR(200) NOT NULL,
        OBSERVACIONES_SOLICITANTE VARCHAR(500),
        CONSTRAINT FK_SOLICITUD_USUARIO FOREIGN KEY( ID_USUARIO) REFERENCES TBL_USUARIOS(ID)
    )
GO
    CREATE TABLE TBL_HISTORIAL(
        ID INT IDENTITY(1, 1) PRIMARY KEY,
        ID_USUARIO INT NOT NULL,
        ID_SOLICITUD INT NOT NULL,
        FECHA DATE NOT NULL,
        OBSERVACIONES VARCHAR(500) NOT NULL,
        ESTADO BIT NOT NULL,
        CONSTRAINT FK_HISTORIAL_USUARIO FOREIGN KEY( ID_USUARIO) REFERENCES TBL_USUARIOS(ID),
        CONSTRAINT FK_HISTORIAL_SOLICITUD FOREIGN KEY (ID_SOLICITUD) REFERENCES TBL_SOLICITUDES(ID)
    )